/*
*   @Class : CI_AccountHelper
*
*   @Author             :   José Ernesto <jose@calibre360.io>
*   @Created            :   06 Oct 2023
*   @Description        :   Clase helper para el objeto Account
*/
public with sharing class CI_AccountHelper {
    //Sector
    public static String SECTOR_OTROS_SERVICIOS     = 'Otros_servicios';

    //Tipo
    public static String TIPO_PARTICULAR            = 'Particular';

    //Subsectores
    public static String SUB_SECTOR_OTROS_SERV_PERS = 'Otros servicios personales';

    public static void cober(){
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
}