/*
*   @Class : CI_GestorProcesos
*
*   @Author             :   José Ernesto <jose@calibre360.io>
*   @Created            :   25 ene 2024
*   @Description        :   Helper Class para los registro Gestor de Proceso
*/
public with sharing class CI_GestorProcesos {
    public final static String ESTADO_CREADO        = 'Creado';
    public final static String ESTADO_EN_PROCESO    = 'En proceso';
    public final static String ESTADO_FINALIZADO    = 'Finalizado';

    public final static String TIPO_REMESA          = 'Generación de Remesa';
}