/*
*   @Class : CI_RemesaEfectoHelper
*
*   @Author             :   José Ernesto <jose@calibre360.io>
*   @Created            :   18 ene 2024
*   @Description        :   Helper Class para los registro juction entre Remesa y Efecto de Cliente
*/
public with sharing class CI_RemesaEfectoHelper {
    public final static String ESTADO_PENDIENTE     = 'Pendiente';
    public final static String ESTADO_PAGADO        = 'Pagado';
    public final static String ESTADO_DEVUELTO      = 'Devuelto';
}